### ISSUE TITLE
reinstalling migrated packages installs to default volume only

### ISSUE THREAD

**Issue by an3k** [OneCDOnly/sherpa#168] opened 2022-01-30 15:11 UTC
Because sherpa automatically installs new versions on every restart of a package I lost every configuration or other user data.

Because sherpa does not check where a package is installed but stupidly installs it into the default location a migration to the correct storage will then overwrite the existing installation including all user data (history, logs, etc. and most importantly the whole configuration.

Thank you.

**Comment by OneCDOnly** [comment] 2022-01-30 21:38
Hey @an3k :)

> Because sherpa does not check where a package is installed but stupidly installs it into the default location a migration to the correct storage will then overwrite the existing installation including all user data (history, logs, etc. and most importantly the whole configuration.

Sorry to hear you've had trouble with this. I know what a PITA it is to lose your config. 😞 

But your description doesn't make a lot of sense to me. Sherpa applications are updated in-place. Even if you've migrated a sherpa QPKG to another volume, it will still be upgraded at the new location (via a simple `git pull`). 

Can you please provide a process to demonstrate the problem so I can confirm it at my end?

Cheers!

**Comment by an3k** [comment] 2022-01-31 09:19
Hi @OneCDOnly , thanks for the quick reply and sympathy :)

In my last ticket I was told how "well" QNAP software behaves in regards to the "Public" share. Yep, that's the culprit again.

When I re-installed my NAS I had my huge but noisy HDDs removed but only two SSDs installed (CACHEDEV1_DATA). Because "Public" was on that drive all apps were installed here. Then I installed my HDDs and moved the share "Public" (and another share) to them (CE_CACHEDEV2_DATA).

When I install apps I either have to migrate them after installation or run qpkg_cli and tell it where to install the app ([#167](https://github.com/OneCDOnly/sherpa/issues/167#issuecomment-1002864198)). It looks like sherpa "just runs the qpkg installer" but doesn't check where the current version is actually installed.

Now my "old" version was installed at /share/CACHEDEV1_DATA/.qpkg/SABnzbd/ while sherpa installed the updated version to /share/CE_CACHEDEV2_DATA/.qpkg/SABnzbd/.
When I noticed the problem I created a copy of my config.ini (but kept it in the same directory ./config/), deleted the content of the updated ./config/ directory and started the migration process. Thanks to QNAP the target directory gets deleted and the source directory gets moved, thus I lost my config.ini as well as the copy I made.

Thankfully, because I got really lazy in the past two years (wonder why) I still had a copy of the whole config directory from a few weeks ago when I freshly re-installed my NAS. I thought I deleted it ... but didn't.

**Comment by OneCDOnly** [comment] 2022-01-31 19:47
Sounds like a rare set of events. Is everything working correctly now?

**Comment by an3k** [comment] 2022-02-01 08:29
It is working now but it will F up again with the next update and restart of the App. Is there a persistent way to disable auto-updates completely?

**Comment by OneCDOnly** [comment] 2022-02-03 06:08
Yup, I can see what happens now. The standard QPKG installation commands included in each QPKG build don't check to see where a package may already be installed, and instead just install it to the default volume. 

Which means we can end up with multiple copies of the same application, but only the original (migrated) will have the correct config info. 

I'll investigate the current sate of `qpkg_cli` as you suggested. Last time I looked at it, it was only partially functional. Many listed options did nothing. Maybe that's changed now.

**Comment by OneCDOnly** [comment] 2022-02-03 06:21
> It is working now but it will F up again with the next update and restart of the App. Is there a persistent way to disable auto-updates completely?

This problem should only occur when a new QPKG version is released, and the old version has been migrated to a volume that's not the default. Once a package has been migrated, it will only update its application via a `git pull` on QPKG start/restart, and it won't matter where the QPKG has been moved to.

**Comment by OneCDOnly** [comment] 2022-02-04 23:31
@an3k I've been looking at this over the last couple of days. It seems using `qpkg_cli` to specify the target volume for a QPKG runs asynchronously and does not permit logging of the QPKG installation process. So, if it fails, there seems to be no-way to work out why. 😞 

As you've previously had some experience with QPKGs, are you aware of any way to install a QPKG to a specific volume without using `qpkg_cli`? Any thoughts please?

**Comment by OneCDOnly** [comment] 2022-02-05 04:47
I've had some success today by modifying the login inside `qinstall.sh` included with QDK. This is compiled into each QPKG and controls the package installation process. 👍🏽 

I now have it checking where the QPKG is currently installed, so it can upgrade the QPKG in-place - even if the QPKG has been migrated to another volume. 🤓 

Still a bit more testing to do, but it looks promising.

**Comment by OneCDOnly** [comment] 2022-02-05 04:56
Thinking: we'll need a basic command-line parser in `qinstall.sh` so the target volume can be specified at install time. This would be handy when a QPKG is to be fully reinstalled (i.e. uninstalled, then installed again). Original installation volume would be saved to a var then specified when installing.

**Comment by OneCDOnly** [comment] 2022-02-06 04:20
Success! 🎉 

After some process tracing, I found it's possible to install a QPKG to a specific location by setting `$QINSTALL_PATH` first.

Example:
```
[/share/Public] # QINSTALL_PATH=/share/CACHEDEV2_DATA/.qpkg sh Par2_0.8.1.0_arm_64.qpkg
```
This gives me something to work with. 👍🏽

**Comment by OneCDOnly** [comment] 2022-02-06 23:19
OK, should be fine now when performing a "simple" QPKG `reinstall`. QPKGs will be reinstalled over themselves in the migrated locations. 👍🏽 

The limitation at the moment is a more "complex" reinstall (i.e. `uninstall` then `install`) won't work, the QPKG will be installed on the default volume as always. I'll work on extending the ability to handle migrated QPKGs with a "complex" reinstall shortly.

**Closed** 2022-02-23 03:46 UTC
Labels: bug, work in progress, confirmed
